INSERT INTO the_climb (location, wall) VALUES ('ISU', '사과');
INSERT INTO the_climb (location, wall) VALUES ('ISU', '배1');
INSERT INTO the_climb (location, wall) VALUES ('ISU', '배2');
INSERT INTO the_climb (location, wall) VALUES ('ISU', '포도');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'ARCH');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'FLAT');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'CAVE');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'ISLAND');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'PROW');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'SLAB');
INSERT INTO the_climb (location, wall) VALUES ('YANGJAE', 'DUNGEON');
INSERT INTO the_climb (location, wall) VALUES ('SUNGSU', '생각');
INSERT INTO the_climb (location, wall) VALUES ('SUNGSU', '성수1');
INSERT INTO the_climb (location, wall) VALUES ('SUNGSU', '성수2');
INSERT INTO the_climb (location, wall) VALUES ('SUNGSU', '공장1');
INSERT INTO the_climb (location, wall) VALUES ('SUNGSU', '공장2');
INSERT INTO the_climb (location, wall) VALUES ('SINLIM', 'MILKYWAY');
INSERT INTO the_climb (location, wall) VALUES ('SINLIM', 'GALAXY OVERHANG');
INSERT INTO the_climb (location, wall) VALUES ('SINLIM', 'GALAXY BALANCE');
INSERT INTO the_climb (location, wall) VALUES ('SINLIM', 'ANDROMEDA');
INSERT INTO the_climb (location, wall) VALUES ('SEOULDAE', 'MARGALEF');
INSERT INTO the_climb (location, wall) VALUES ('SEOULDAE', 'ARHI');
INSERT INTO the_climb (location, wall) VALUES ('SEOULDAE', 'CONE');
INSERT INTO the_climb (location, wall) VALUES ('SEOULDAE', 'HEXAGON');
INSERT INTO the_climb (location, wall) VALUES ('NONHYEON', '논');
INSERT INTO the_climb (location, wall) VALUES ('NONHYEON', '고개1');
INSERT INTO the_climb (location, wall) VALUES ('NONHYEON', '고개2');
INSERT INTO the_climb (location, wall) VALUES ('NONHYEON', '밭');
INSERT INTO the_climb (location, wall) VALUES ('NONHYEON', '작은 밭');
INSERT INTO the_climb (location, wall) VALUES ('SINSA', '가로수');
INSERT INTO the_climb (location, wall) VALUES ('SINSA', '나로수');
INSERT INTO the_climb (location, wall) VALUES ('SINSA', '다로수');
INSERT INTO the_climb (location, wall) VALUES ('SINSA', '세로수');
INSERT INTO the_climb (location, wall) VALUES ('YEONNAM', '연남');
INSERT INTO the_climb (location, wall) VALUES ('YEONNAM', '툇마루');
INSERT INTO the_climb (location, wall) VALUES ('YEONNAM', '신촌');
INSERT INTO the_climb (location, wall) VALUES ('MAGOK', '1&2');
INSERT INTO the_climb (location, wall) VALUES ('MAGOK', '3&4');
INSERT INTO the_climb (location, wall) VALUES ('MAGOK', '5&6');
INSERT INTO the_climb (location, wall) VALUES ('MAGOK', '7&8');
INSERT INTO the_climb (location, wall) VALUES ('SADANG', '관악1');
INSERT INTO the_climb (location, wall) VALUES ('SADANG', '관악2');
INSERT INTO the_climb (location, wall) VALUES ('SADANG', '동작1');
INSERT INTO the_climb (location, wall) VALUES ('SADANG', '동작2');
INSERT INTO the_climb (location, wall) VALUES ('SADANG', '서초');
INSERT INTO the_climb (location, wall) VALUES ('MULLAE', '집게');
INSERT INTO the_climb (location, wall) VALUES ('MULLAE', '망치');
INSERT INTO the_climb (location, wall) VALUES ('MULLAE', '도가니');
INSERT INTO the_climb (location, wall) VALUES ('MULLAE', '강철');
INSERT INTO the_climb (location, wall) VALUES ('MULLAE', '모루');
INSERT INTO the_climb (location, wall) VALUES ('HONGDAE', '1-1');
INSERT INTO the_climb (location, wall) VALUES ('HONGDAE', '1-2');
INSERT INTO the_climb (location, wall) VALUES ('HONGDAE', '2-1');
INSERT INTO the_climb (location, wall) VALUES ('HONGDAE', '2-2');
INSERT INTO the_climb (location, wall) VALUES ('ILSAN', 'NEW WAVE');
INSERT INTO the_climb (location, wall) VALUES ('ILSAN', 'WHITE WALL');
INSERT INTO the_climb (location, wall) VALUES ('ILSAN', 'ISLAND A');
INSERT INTO the_climb (location, wall) VALUES ('ILSAN', 'ISLAND B');
INSERT INTO the_climb (location, wall) VALUES ('ILSAN', 'COMPETITION WALL');
INSERT INTO the_climb (location, wall) VALUES ('GANGNAM', '1&2');
INSERT INTO the_climb (location, wall) VALUES ('GANGNAM', '3&4');
INSERT INTO the_climb (location, wall) VALUES ('GANGNAM', '5&6');
INSERT INTO the_climb (location, wall) VALUES ('GANGNAM', '7&8');
INSERT INTO the_climb (location) VALUES ('ISU');
INSERT INTO the_climb (location) VALUES ('YANGJAE');
INSERT INTO the_climb (location) VALUES ('SUNGSU');
INSERT INTO the_climb (location) VALUES ('SINLIM');
INSERT INTO the_climb (location) VALUES ('SEOULDAE');
INSERT INTO the_climb (location) VALUES ('NONHYEON');
INSERT INTO the_climb (location) VALUES ('SINSA');
INSERT INTO the_climb (location) VALUES ('YEONNAM');
INSERT INTO the_climb (location) VALUES ('MAGOK');
INSERT INTO the_climb (location) VALUES ('SADANG');
INSERT INTO the_climb (location) VALUES ('MULLAE');
INSERT INTO the_climb (location) VALUES ('HONGDAE');
INSERT INTO the_climb (location) VALUES ('ILSAN');
INSERT INTO the_climb (location) VALUES ('GANGNAM');
