INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '사과', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '배2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('이수', '포도', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ARCH', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'FLAT', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'CAVE', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'ISLAND', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'PROW', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'SLAB', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('양재', 'DUNGEON', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '생각', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '성수2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('성수', '공장2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'MILKYWAY', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY OVERHANG', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'GALAXY BALANCE', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신림', 'ANDROMEDA', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'MARGALEF', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'ARHI', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'CONE', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('서울대', 'HEXAGON', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '논', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '고개2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '밭', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('논현', '작은 밭', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '가로수', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '나로수', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '다로수', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('신사', '세로수', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '연남', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '툇마루', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('연남', '신촌', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '1&2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '3&4', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '5&6', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('마곡', '7&8', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '관악2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '동작2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('사당', '서초', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '집게', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '망치', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '도가니', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '강철', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('문래', '모루', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '1-2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-1', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('홍대', '2-2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'NEW WAVE', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'WHITE WALL', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND A', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'ISLAND B', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('일산', 'COMPETITION WALL', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '1&2', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '3&4', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '5&6', '검정');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '하양');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '노랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '주황');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '초록');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '파랑');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '빨강');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '보라');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '회색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '갈색');
INSERT INTO the_climb (name, wall, color) VALUES ('강남', '7&8', '검정');