INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '사과', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '배2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ISU', '포도', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ARCH', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'FLAT', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'CAVE', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'ISLAND', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'PROW', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'SLAB', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YANGJAE', 'DUNGEON', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '생각', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '성수2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SUNGSU', '공장2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'MILKYWAY', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY OVERHANG', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'GALAXY BALANCE', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINLIM', 'ANDROMEDA', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'MARGALEF', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'ARHI', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'CONE', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SEOULDAE', 'HEXAGON', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '논', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '고개2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '밭', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('NONHYEON', '작은 밭', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '가로수', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '나로수', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '다로수', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SINSA', '세로수', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '연남', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '툇마루', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('YEONNAM', '신촌', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '1&2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '3&4', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '5&6', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MAGOK', '7&8', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '관악2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '동작2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('SADANG', '서초', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '집게', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '망치', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '도가니', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '강철', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('MULLAE', '모루', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '1-2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-1', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('HONGDAE', '2-2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'NEW WAVE', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'WHITE WALL', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND A', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'ISLAND B', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('ILSAN', 'COMPETITION WALL', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '1&2', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '3&4', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '5&6', 'BLACK');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'WHITE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'YELLOW');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'ORANGE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'GREEN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'BLUE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'RED');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'PURPLE');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'GREY');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'BROWN');
INSERT INTO the_climb (name, wall, color) VALUES ('GANGNAM', '7&8', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'RED');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('ISU', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'RED');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('YANGJAE', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'RED');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('SUNGSU', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'RED');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('SINLIM', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'RED');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('SEOULDAE', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'RED');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('NONHYEON', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'RED');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('SINSA', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'RED');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('YEONNAM', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'RED');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('MAGOK', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'RED');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('SADANG', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'RED');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('MULLAE', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'RED');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('HONGDAE', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'RED');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('ILSAN', 'BLACK');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'WHITE');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'YELLOW');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'ORANGE');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'GREEN');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'BLUE');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'RED');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'PURPLE');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'GREY');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'BROWN');
INSERT INTO the_climb (name, color) VALUES ('GANGNAM', 'BLACK');